version: "3.8"

services:
  # Backend API with MongoDB Cloud
  backend:
    build: ./backend
    container_name: travel_backend
    environment:
      MONGODB_URI: mongodb+srv://hiendang:<db_password>@cluster0.83zr5s5.mongodb.net/travel_app?retryWrites=true&w=majority
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - travel_network
    restart: unless-stopped

  # Frontend (cho phát triển)
  frontend:
    build: ./frontend
    container_name: travel_frontend
    environment:
      VITE_BACKEND_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - travel_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

networks:
  travel_network:
    driver: bridge
